'use client';

import { useState } from 'react';
import { useAccount, useWriteContract, useWaitForTransactionReceipt } from 'wagmi';
import { parseEther } from 'viem';

// ABI placeholders - in a real app, import from a JSON artifact generated by Hardhat
const MonadMonsABI = [
    { "inputs": [], "name": "mintStarter", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [], "name": "claimDaily", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [], "name": "buyCard", "outputs": [], "stateMutability": "payable", "type": "function" }
];

const MONAD_MONS_ADDRESS = '0xb304e21E368cCe3e8F8367e1Bb143E90bb3F0512'; // From local deploy

export default function Shop() {
    const { isConnected } = useAccount();
    const { data: hash, writeContract, isPending } = useWriteContract();
    const { isLoading: isConfirming, isSuccess } = useWaitForTransactionReceipt({ hash });

    const handleMintStarter = () => writeContract({ abi: MonadMonsABI, address: MONAD_MONS_ADDRESS, functionName: 'mintStarter' });
    const handleClaimDaily = () => writeContract({ abi: MonadMonsABI, address: MONAD_MONS_ADDRESS, functionName: 'claimDaily' });
    const handleBuyPremium = () => writeContract({ abi: MonadMonsABI, address: MONAD_MONS_ADDRESS, functionName: 'buyCard', value: parseEther('0.1') });

    if (!isConnected) {
        return (
            <div className="flex flex-col items-center justify-center min-h-[calc(100vh-64px)] px-4">
                <h2 className="text-3xl font-bold bg-gradient-to-r from-red-500 to-orange-500 bg-clip-text text-transparent">Please Connect Wallet</h2>
                <p className="mt-4 text-zinc-400">You must be connected to the Monad Testnet to access the Shop.</p>
            </div>
        );
    }

    return (
        <div className="max-w-6xl mx-auto px-4 py-12">
            <h1 className="text-4xl font-extrabold mb-2 bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">Shop & Claim</h1>
            <p className="text-zinc-400 mb-12">Acquire new MonadMons to expand your deck and dominate the arena.</p>

            {isSuccess && (
                <div className="mb-8 p-4 rounded-xl bg-green-500/10 border border-green-500/50 text-green-400 font-medium text-center">
                    Transaction Successful! Your new MonadMon is on its way.
                </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {/* Starter Pack */}
                <div className="flex flex-col p-8 rounded-3xl bg-zinc-900 border border-white/5 relative overflow-hidden group hover:border-indigo-500/50 transition-colors">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-blue-500 to-indigo-500" />
                    <h3 className="text-2xl font-bold mb-2">Starter Pack</h3>
                    <p className="text-zinc-400 mb-6 flex-grow">New to the game? Claim your completely free starter card to begin your journey.</p>
                    <div className="text-3xl font-bold mb-6">Free</div>
                    <button
                        disabled={isPending || isConfirming}
                        onClick={handleMintStarter}
                        className="w-full py-4 rounded-xl font-bold bg-white/10 hover:bg-white/20 transition-colors disabled:opacity-50"
                    >
                        {isPending ? 'Confirming...' : 'Mint Starter'}
                    </button>
                </div>

                {/* Daily Drop */}
                <div className="flex flex-col p-8 rounded-3xl bg-zinc-900 border border-white/5 relative overflow-hidden group hover:border-purple-500/50 transition-colors">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-500 to-pink-500" />
                    <h3 className="text-2xl font-bold mb-2">Daily Drop</h3>
                    <p className="text-zinc-400 mb-6 flex-grow">Returns every 24 hours. A guaranteed Standard-tier card to bolster your collection.</p>
                    <div className="text-3xl font-bold mb-6">Free</div>
                    <button
                        disabled={isPending || isConfirming}
                        onClick={handleClaimDaily}
                        className="w-full py-4 rounded-xl font-bold bg-purple-500 hover:bg-purple-600 transition-colors disabled:opacity-50 shadow-[0_0_20px_-5px_rgba(168,85,247,0.5)]"
                    >
                        {isPending ? 'Claiming...' : 'Claim Daily'}
                    </button>
                </div>

                {/* Premium Mint */}
                <div className="flex flex-col p-8 rounded-3xl bg-zinc-900 border border-amber-500/20 relative overflow-hidden group hover:border-amber-500/80 transition-colors">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-amber-400 to-orange-500" />
                    <div className="absolute top-4 right-4 bg-amber-500/20 text-amber-400 text-xs font-bold px-2 py-1 rounded">HOT</div>
                    <h3 className="text-2xl font-bold mb-2 text-amber-100">Premium Summon</h3>
                    <p className="text-zinc-400 mb-6 flex-grow">Purchase a premium high-stat MonadMon card using Monad test tokens.</p>
                    <div className="text-3xl font-bold mb-6 text-amber-400">0.1 MON</div>
                    <button
                        disabled={isPending || isConfirming}
                        onClick={handleBuyPremium}
                        className="w-full py-4 rounded-xl font-bold bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-400 hover:to-orange-400 text-stone-900 transition-colors disabled:opacity-50 shadow-[0_0_20px_-5px_rgba(245,158,11,0.5)]"
                    >
                        {isPending ? 'Minting...' : 'Buy Premium'}
                    </button>
                </div>
            </div>
        </div>
    );
}
