'use client';

import { useAccount, useWriteContract, useWaitForTransactionReceipt } from 'wagmi';
import { parseEther } from 'viem';
import Image from 'next/image';
import { GlareCard } from '@/components/ui/glare-card';

// ABI placeholders - in a real app, import from a JSON artifact generated by Hardhat
const MonadMonsABI = [
    { "inputs": [{ "internalType": "uint8", "name": "_speciesId", "type": "uint8" }], "name": "mintStarter", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [{ "internalType": "uint8", "name": "_speciesId", "type": "uint8" }], "name": "claimDaily", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
    { "inputs": [{ "internalType": "uint8", "name": "_speciesId", "type": "uint8" }], "name": "buyCard", "outputs": [], "stateMutability": "payable", "type": "function" }
];

const MONAD_MONS_ADDRESS = '0xdcB7bD581BABF76ea8530E11b00E29988032Bea8'; // Updated to new deployment

// Define the Pokemon we want to sell in the Premium shop
const POKEMON_PRODUCTS = [
    {
        name: 'Charizard',
        image: '/images/charizaed.png',
        type: 'Fire / Flying',
        gradient: 'from-orange-500 to-red-600',
        textColor: 'text-orange-400',
    },
    {
        name: 'Blastoise',
        image: '/images/blastois.png',
        type: 'Water',
        gradient: 'from-blue-500 to-cyan-500',
        textColor: 'text-blue-400',
    },
    {
        name: 'Venusaur',
        image: '/images/venasaur.png',
        type: 'Grass / Poison',
        gradient: 'from-green-500 to-emerald-600',
        textColor: 'text-green-400',
    },
    {
        name: 'Pikachu',
        image: '/images/pikachu.png',
        type: 'Electric',
        gradient: 'from-yellow-400 to-amber-500',
        textColor: 'text-yellow-400',
    }
];

export default function Shop() {
    const { isConnected } = useAccount();
    const { data: hash, writeContract, isPending, error: writeError } = useWriteContract();
    const { isLoading: isConfirming, isSuccess, error: receiptError } = useWaitForTransactionReceipt({ hash });

    const handleBuyPremium = (speciesId: number) => {
        try {
            writeContract({
                abi: MonadMonsABI,
                address: MONAD_MONS_ADDRESS,
                functionName: 'buyCard',
                args: [speciesId],
                value: parseEther('0.1')
            }, {
                onError(err) {
                    console.error('Minting error details:', err);
                }
            });
        } catch (err) {
            console.error('Failed to invoke writeContract:', err);
        }
    };

    if (!isConnected) {
        return (
            <div className="flex flex-col items-center justify-center min-h-[calc(100vh-64px)] px-4">
                <h2 className="text-3xl font-bold bg-gradient-to-r from-red-500 to-orange-500 bg-clip-text text-transparent">Please Connect Wallet</h2>
                <p className="mt-4 text-zinc-400">You must be connected to the Monad Testnet to access the Shop.</p>
            </div>
        );
    }

    return (
        <div className="max-w-7xl mx-auto px-4 py-12">
            <h1 className="text-5xl font-black mb-4 bg-gradient-to-r from-yellow-400 via-yellow-200 to-amber-500 bg-clip-text text-transparent text-center">
                Premium Pokémon Mint
            </h1>
            <p className="text-zinc-400 mb-8 text-center text-lg max-w-2xl mx-auto">
                Acquire legendary, high-stat Pokémon to dominate the battle arena. Each card requires 0.1 MON and holds immense power.
            </p>

            <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4 max-w-3xl mx-auto mb-16 text-center text-amber-200/80 text-sm">
                <span className="font-bold text-amber-400">Note:</span> The MonadMons smart contract utilizes block-timestamp randomness. Minting from this premium selection guarantees a <span className="text-amber-400 font-mono">Tier.Premium</span> NFT with massive base stats, but its exact elemental affinity and final stat distribution will be forged upon transaction confirmation.
            </div>

            {isSuccess && (
                <div className="max-w-2xl mx-auto mb-12 p-4 rounded-xl bg-green-500/10 border border-green-500/50 text-green-400 font-medium text-center shadow-[0_0_20px_-5px_rgba(34,197,94,0.3)]">
                    Transaction Successful! Your new Premium Pokémon has been minted to your wallet. You can view it in the Health Centre.
                </div>
            )}

            {(writeError || receiptError) && (
                <div className="max-w-3xl mx-auto mb-12 p-6 rounded-xl bg-red-500/10 border border-red-500/50 text-red-400 font-medium whitespace-pre-wrap break-all shadow-[0_0_20px_-5px_rgba(239,68,68,0.3)]">
                    <h3 className="text-lg font-bold text-red-500 mb-2">Transaction Failed</h3>
                    <p className="text-sm font-mono opacity-80">{writeError?.message || receiptError?.message}</p>
                </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 place-items-center">
                {POKEMON_PRODUCTS.map((pokemon, idx) => (
                    <div key={idx} className="flex flex-col items-center w-full max-w-[320px]">

                        <div className="w-full relative mb-6">
                            <GlareCard className="flex flex-col items-center justify-center px-6 py-8">
                                <div className="absolute inset-0 z-0 opacity-20 bg-gradient-to-b from-transparent to-black rounded-[48px]" />

                                <h3 className={`text-3xl font-bold mb-1 z-10 ${pokemon.textColor}`}>{pokemon.name}</h3>
                                <p className="text-white/60 text-sm tracking-widest uppercase font-bold mb-8 z-10">{pokemon.type}</p>

                                <div className="relative w-full aspect-square z-10 drop-shadow-2xl hover:scale-110 transition-transform duration-500">
                                    <Image
                                        src={pokemon.image}
                                        alt={pokemon.name}
                                        fill
                                        sizes="(max-width: 768px) 100vw, 320px"
                                        className="object-contain filter drop-shadow-[0_20px_20px_rgba(0,0,0,0.8)]"
                                    />
                                </div>

                                <div className="absolute bottom-6 w-full text-center z-10">
                                    <p className="text-white font-mono font-bold text-xl drop-shadow-md">Tier: PREMIUM</p>
                                </div>
                            </GlareCard>
                        </div>

                        <button
                            disabled={isPending || isConfirming}
                            onClick={() => handleBuyPremium(idx)}
                            className={`w-full py-4 rounded-xl font-bold bg-gradient-to-r ${pokemon.gradient} text-white transition-all transform hover:scale-105 active:scale-95 disabled:opacity-50 shadow-lg`}
                        >
                            {isPending || isConfirming ? 'Minting...' : 'Buy Premium (0.1 MON)'}
                        </button>

                    </div>
                ))}
            </div>

            <div className="mt-20 border-t border-white/10 pt-12 flex justify-center gap-8 text-center bg-zinc-900/50 px-8 py-8 rounded-3xl backdrop-blur-md">
                <div className="flex flex-col items-center max-w-[300px]">
                    <h3 className="text-2xl font-bold mb-2 text-white">Starter Pack</h3>
                    <p className="text-zinc-500 mb-6 text-sm">New here? Claim a free starter.</p>
                    <button className="px-8 py-3 rounded-lg font-bold bg-white/5 hover:bg-white/10 text-white transition-colors border border-white/10">Free Claim</button>
                </div>
                <div className="w-px bg-white/10"></div>
                <div className="flex flex-col items-center max-w-[300px]">
                    <h3 className="text-2xl font-bold mb-2 text-purple-400">Daily Drop</h3>
                    <p className="text-zinc-500 mb-6 text-sm">Returns every 24 hours.</p>
                    <button className="px-8 py-3 rounded-lg font-bold bg-purple-600 hover:bg-purple-500 text-white transition-colors shadow-lg shadow-purple-900/50">Claim Daily</button>
                </div>
            </div>
        </div>
    );
}
